# Generated by Django 3.0.4 on 2020-03-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backups',
            name='fyle_org_id',
            field=models.CharField(help_text='Organisation id in Fyle', max_length=255, null=True),
        ),
    ]
