# Generated by Django 3.0.4 on 2020-03-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_auto_20200316_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backups',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
