# Generated by Django 3.0.4 on 2020-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_auto_20200316_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='backups',
            name='file_path',
            field=models.CharField(help_text='Cloud storage URL for this backup', max_length=512, null=True),
        ),
    ]
