# Generated by Django 3.0.4 on 2020-06-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_remove_backups_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backups',
            name='fyle_file_id',
            field=models.CharField(
                help_text='File ID of file', max_length=255, null=True),
        ),
    ]
