# Generated by Django 3.0.4 on 2020-03-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_backups_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backups',
            name='fyle_org_id',
            field=models.CharField(default='org_id', help_text='Organisation id in Fyle', max_length=255),
            preserve_default=False,
        ),
    ]
