# Generated by Django 3.0.4 on 2020-07-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_auto_20200605_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='backups',
            name='attachment_state',
            field=models.CharField(help_text='Current state of backup', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='backups',
            name='split_count',
            field=models.IntegerField(help_text='Count of attachment segments of a Job', null=True),
        ),
        migrations.AlterField(
            model_name='backups',
            name='fyle_file_id',
            field=models.TextField(help_text='File ID of file', null=True),
        ),
    ]
