# Generated by Django 3.0.4 on 2020-03-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backups', '0005_auto_20200321_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='backups',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backups',
            name='fyle_org_id',
            field=models.CharField(help_text='Fyle org_id of backup requester', max_length=255),
        ),
        migrations.AlterField(
            model_name='backups',
            name='fyle_refresh_token',
            field=models.CharField(help_text='Fyle Refresh Token', max_length=512),
        ),
    ]
