# Generated by Django 3.0.4 on 2020-07-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_auto_20200714_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backups',
            name='attachment_state',
        ),
    ]
