# Generated by Django 3.0.4 on 2020-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(help_text='Refresh Token', max_length=512, null=True),
        ),
    ]
