# Generated by Django 3.0.4 on 2020-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_fyle_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fyle_org_id',
            field=models.CharField(help_text='Fyle org id of current active account', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='refresh_token',
            field=models.CharField(help_text='Fyle refresh token of current active account', max_length=512, null=True),
        ),
    ]
